### PR TITLE
Fail tests with nested effects

### LINKED ISSUE #159: CatsEffectSuite runs inner IO if it receives IO[IO[A]]
A colleague of mine spent hours fighting with Resource in a test due to a trivial mistake (`map` vs `flatMap`).
I've found out that CatsEffectSuite does something _really_ odd in this case however: it seems to run `unsafeToFuture` on both the outer _and_ inner `IO` when it receives `IO[IO[A]]`, maybe there is some implicit conversion happening.
The repro should make it clear:

```scala
import cats.effect._
import munit.CatsEffectSuite
import scala.concurrent.duration._

class Repro extends CatsEffectSuite {
  test("use after close") {
    Resource.make(IO.println("Open"))(_ => IO.println("Close")).use { _ =>
      IO.println("Enjoy: ").map { _ =>
        IO.sleep(1.second) >> IO.println("Use after close!")
      }
    }
  }

  test("minimised") {
    IO.println("Nope")
    IO.println("Hello").map { _ => IO.println("Surely not") }
  }
}

/*
sbt:root> testOnly *Repro*
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for Test / testOnly
Open
Enjoy: 
Close
Use after close!
Repro:
  + use after close 1.105s
Hello
Surely not
  + minimised 0.002s
[info] Passed: Total 2, Failed 0, Errors 0, Passed 2
[success] Total time: 1 s, completed 30 Nov 2021, 14:48:32
*/

```

### PR DESCRIPTION
**Pull request by SystemFw**
Fixes #159

### CODE REVIEW

File: ce2/shared/src/main/scala/munit/CatsEffectSuite.scala [hunk 1]
```diff
@@ -39,15 +39,72 @@ abstract class CatsEffectSuite
...
+  //
+  // Unfortunately, this has an unforeseen consequence in CatsEffectSuite:
+  // if you return `IO[IO[A]]` by accident, for example by using `map` instead of `flatMap`,
+  // MUnit will execute both the inner and outer `IO` by applying our `IO` transform twice.
+  //
+  // This breaks the `IO` mental model, and can lead to very surprising behaviour, e.g see:
+  //  https://github.com/typelevel/munit-cats-effect/issues/159.
+  //
+  // This method checks for such a case, and fails the test with an actionable message.
+  private def checkNestingIO(fa: IO[_]): IO[Any] = {
```
Comment (danicheg) [inline ce2/shared/src/main/scala/munit/CatsEffectSuite.scala:62]: Perhaps we could have `checkNestingIO` and `checkNestingSyncIO` in the common module? IIUC, they haven't nor CE2-specific, nor CE3-specific stuff.

Comment (SystemFw) [reply ce2/shared/src/main/scala/munit/CatsEffectSuite.scala:62]: Yeah I think we can do that. Not too sure where to put them though

**Review by danicheg — APPROVED** [review]
Though this means behavior changes, it's right to fail tests with nested effects, I think.
