### PR TITLE
Pure ResourceFixture and complementary syntax

### LINKED ISSUE #60: Promise exception on 2.12
In one of my tests I'm using a fixture and I see these messages on the log, surprisingly in 2.12 only and the error itself runs fine it just print these

```
java.lang.IllegalStateException: Promise already completed.
  | => oat scala.concurrent.Promise.complete(Promise.scala:53)
        at scala.concurrent.Promise.complete$(Promise.scala:52)
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
        at scala.concurrent.Promise.failure(Promise.scala:104)
        at scala.concurrent.Promise.failure$(Promise.scala:104)
        at scala.concurrent.impl.Promise$DefaultPromise.failure(Promise.scala:187)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:45)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at munit.Suite$$anon$1.execute(Suite.scala:26)
```

The error itself is kind of complicated but I could try to produce a minimal reproduction in needed

### PR DESCRIPTION
**Pull request by RaasAhsan**
Fixes #60

### CODE REVIEW

File: common/shared/src/main/scala/munit/CatsEffectFunFixtures.scala [hunk 1]
```diff
@@ -64,4 +64,18 @@ trait CatsEffectFunFixtures extends FunFixtures { self: CatsEffectSuite =>
 
   }
 
+  implicit class SyncIOFunFixtureOps[T](private val fixture: SyncIO[FunFixture[T]]) {
```
Comment (RaasAhsan) [inline common/shared/src/main/scala/munit/CatsEffectFunFixtures.scala:67]: unfortunately nested classes can't be declared `AnyVal`.. and `FunFixture` is a private type within `FunFixture` so we can't stick it in the companion object either. maybe there's some twisted way to do this

**Review by milanvdm — APPROVED** [review]

**Review by mpilquist — APPROVED** [review]
